name: Check

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  schedule:
  - cron: "*/20 * * * *"

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Repository
      uses: actions/checkout@v3
    - name: Setup Deno
      uses: denoland/setup-deno@v1
    - name: Run Deno
      env: ${{ secrets }}
      run: deno run --allow-all ./sync.ts
