name: Check

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  schedule:
  - cron: "*/10 * * * *"

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Repository
      uses: actions/checkout@v3

    - name: Setup Deno
      uses: denoland/setup-deno@v1

    - name: Load DB cache
      uses: actions/cache@v3
      with:
        key: database
        path: data.sqlite

    - name: Run Deno
      env: ${{ secrets }}
      run: deno run --allow-all ./sync.ts

    - name: Upload DB cache
      uses: actions/cache@v3
      with:
        key: database
        path: data.sqlite
