name: Sync

on:
  workflow_dispatch:
  schedule:
  - cron: "*/10 * * * *"

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Repository
      uses: actions/checkout@v3

    - name: Demo cache
      uses: actions/cache@v3
      with:
        key: deno
        path: |
          ~/.deno
          ~/.cache/deno

    - name: Setup Deno
      uses: denoland/setup-deno@v1

    - name: Database cache
      uses: actions/cache@v3
      with:
        key: database
        path: data.sqlite

    - name: Run Deno
      env: ${{ secrets }}
      run: deno run --allow-all ./sync.ts
