name: Check

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  schedule:
  - cron: "*/30 * * * *"

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Repository
      uses: actions/checkout@v3
    - name: Setup Deno
      uses: denoland/setup-deno@v1
    - name: Run Deno
      run: env & deno run --allow-all ./sync.ts
